### ISSUE TITLE
kanban bored setup

### ISSUE THREAD

**Issue by frnega** [frnega/capstone-JavaScript#21]
https://github.com/frnega/capstone-JavaScript

in this issue, we implemented a kanban board set up with two people. the group of this capstone project include only two people so we removed all tasks with student c. student A is frehiywot nega and student B is Ifeanyi joseph oti.

regards.

**Comment by emmiiorji** [comment]
Hi Team, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats-14](https://user-images.githubusercontent.com/20554583/203123153-d9df7ec7-8773-44fb-b7ad-290379a5a3b8.gif)

## Good Highlights✔

- Kanban board has been set up properly


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
